name: Tauri App CI

on:
    push:
      branches:
        - '*'
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    shell: bash

# Declare default permissions as read only.
permissions: write-all

env:
  NODE_ENV: production
  NODE_VERSION: 18
  APP_NAME: desmos_app
  RELEASE_VERSION: '' # Just for silent github-action lint
  BUILD_DIR: '..'

jobs:
    build-tauri-app:
        name: 'Build native executable'
        if: contains(github.ref, 'tags')
        strategy:
          fail-fast: false
          matrix:
            platform: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{matrix.platform}}
        steps:
          - name: 'Checkout'
            uses: actions/checkout@v2
            with:
              submodules: false
          - name: set version env
            run: |
              GITHUB_REF_NAME=${{github.ref_name}}
              echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
              echo "set env.RELEASE_VERSION to ${GITHUB_REF_NAME#v}"
          - name: generate/overwrite package.json
            run: |
              # generate/overwrite package.json
              cat <<- EOF > package.json
              {
                "name": "${{env.APP_NAME}}",
                "version": "${{env.RELEASE_VERSION}}"
              }
              EOF
              # npm --no-git-tag-version version -f ${{env.RELEASE_VERSION}}
              cat package.json
              cat <<- EOF > custom-config.json
              {"package":{"productName":"${{env.APP_NAME}}", "version":"${{env.RELEASE_VERSION}}"}, "build":{"distDir":"../${{env.BUILD_DIR}}", "beforeBuildCommand":""}}
              EOF
              cat custom-config.json
          - name: Display structure of root
            run: ls -la . ${{env.BUILD_DIR}}
          # - name: setup Node.js ${{env.NODE_VERSION}}
          #   uses: actions/setup-node@v3
          #   with:
          #     node-version: ${{env.NODE_VERSION}}
          #     cache: 'npm'
          - name: setup Rust stable
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
          - name: install dependencies (ubuntu only)
            if: matrix.platform == 'ubuntu-latest'
            run: |
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf 
          - uses: liudonghua123/tauri-action@dev
            name: package and deploy app
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              distPath: ${{env.BUILD_DIR}}
              tagName: ${{github.ref_name}}
              releaseName: ${{github.ref_name}}
              releaseBody: "Choose the correct app for your platform, download and run!"
              bundleIdentifier: www.desmos.com
              args: -c custom-config.json
              releaseDraft: false
              prerelease: false
              productName: ${{env.APP_NAME}}
              version: ${{env.RELEASE_VERSION}}